### ISSUE TITLE
Chapter: Installation

### ISSUE THREAD

**Issue by am11** [am11/NDL-VuFind#1]
Hello @samuli.

I am installing VuFind using WAMP on Windows and on VM, I am using headless Ubuntu 12 (shell-only) via [vagrant](http://vagrantup.com/).

Going by this guide: https://vufind.org/wiki/installation_windows under SolarMarc, I can't locate `import.properties` file. Is it obsolete?

On that note, do we need MARC records for API implementation?

This is just a rehearsal. We will probably installing again on Mac tomorrow morning at around 9:00.

Thanks.

**Comment by Lissie** [comment]
Currently doing the installation in Mac system. Having problems activating the pear command.

**Comment by am11** [comment]
@Lissie,

First install virtualbox.

Then go to http://vagrantup.com/ and install vagrant.

To install 64-bit Ubuntu:

``` bash
vagrant init hashicorp/precise64

vagrant up
```

To run it:

``` bash
vagrant ssh # in the directory where Ubuntu is downloaded
```
